/**
 * This file is auto-generated by scripts/update-open-router-data.ts. Do not
 * edit manually.
 *
 * Last updated: 2025-07-19T12:00:35.578Z
 */

import type { SupportedModelNames } from '../types/supported-model-names'
import type { ModelRouterData } from '../types/model-router-data'

export let openRouterModels: Record<SupportedModelNames, ModelRouterData> = {
  'claude-3.7-sonnet': {
    canonicalSlug: 'anthropic/claude-3-7-sonnet-20250219',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    name: 'claude-3.7-sonnet',
    costPer1kTokens: 0.003,
    contextWindow: 200000,
    source: 'openrouter',
  },
  'claude-sonnet-4': {
    canonicalSlug: 'anthropic/claude-4-sonnet-20250522',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    name: 'claude-sonnet-4',
    costPer1kTokens: 0.003,
    contextWindow: 200000,
    source: 'openrouter',
  },
  'claude-3.5-sonnet': {
    canonicalSlug: 'anthropic/claude-3.5-sonnet',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    name: 'claude-3.5-sonnet',
    costPer1kTokens: 0.003,
    contextWindow: 200000,
    source: 'openrouter',
  },
  'claude-3.5-haiku': {
    canonicalSlug: 'anthropic/claude-3-5-haiku',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    name: 'claude-3.5-haiku',
    costPer1kTokens: 0.0008,
    contextWindow: 200000,
    source: 'openrouter',
  },
  'claude-opus-4': {
    canonicalSlug: 'anthropic/claude-4-opus-20250522',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    costPer1kTokens: 0.015,
    name: 'claude-opus-4',
    contextWindow: 200000,
    source: 'openrouter',
  },
  'gpt-4.1-mini': {
    canonicalSlug: 'openai/gpt-4.1-mini-2025-04-14',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    costPer1kTokens: 0.0004,
    contextWindow: 1047576,
    name: 'gpt-4.1-mini',
    source: 'openrouter',
  },
  'gpt-4.1-nano': {
    canonicalSlug: 'openai/gpt-4.1-nano-2025-04-14',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    costPer1kTokens: 0.0001,
    contextWindow: 1047576,
    name: 'gpt-4.1-nano',
    source: 'openrouter',
  },
  'claude-3-opus': {
    canonicalSlug: 'anthropic/claude-3-opus',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    costPer1kTokens: 0.015,
    name: 'claude-3-opus',
    contextWindow: 200000,
    source: 'openrouter',
  },
  'gpt-3.5-turbo': {
    lastUpdated: '2025-07-19T12:00:35.577Z',
    canonicalSlug: 'openai/gpt-3.5-turbo',
    costPer1kTokens: 0.0005,
    name: 'gpt-3.5-turbo',
    contextWindow: 16385,
    source: 'openrouter',
  },
  'gpt-4o-mini': {
    lastUpdated: '2025-07-19T12:00:35.578Z',
    canonicalSlug: 'openai/gpt-4o-mini',
    costPer1kTokens: 0.00015,
    contextWindow: 128000,
    source: 'openrouter',
    name: 'gpt-4o-mini',
  },
  'gpt-4.1': {
    canonicalSlug: 'openai/gpt-4.1-2025-04-14',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    costPer1kTokens: 0.002,
    contextWindow: 1047576,
    source: 'openrouter',
    name: 'gpt-4.1',
  },
  'o3-mini': {
    canonicalSlug: 'openai/o3-mini-2025-01-31',
    lastUpdated: '2025-07-19T12:00:35.578Z',
    costPer1kTokens: 0.0011,
    contextWindow: 200000,
    source: 'openrouter',
    name: 'o3-mini',
  },
  'gpt-4-turbo': {
    lastUpdated: '2025-07-19T12:00:35.578Z',
    canonicalSlug: 'openai/gpt-4-turbo',
    costPer1kTokens: 0.01,
    contextWindow: 128000,
    source: 'openrouter',
    name: 'gpt-4-turbo',
  },
  'o1-mini': {
    lastUpdated: '2025-07-19T12:00:35.578Z',
    canonicalSlug: 'openai/o1-mini',
    costPer1kTokens: 0.0011,
    contextWindow: 128000,
    source: 'openrouter',
    name: 'o1-mini',
  },
  'gpt-4o': {
    lastUpdated: '2025-07-19T12:00:35.578Z',
    canonicalSlug: 'openai/gpt-4o',
    costPer1kTokens: 0.0025,
    contextWindow: 128000,
    source: 'openrouter',
    name: 'gpt-4o',
  },
  o1: {
    lastUpdated: '2025-07-19T12:00:35.578Z',
    canonicalSlug: 'openai/o1-2024-12-17',
    costPer1kTokens: 0.015,
    contextWindow: 200000,
    source: 'openrouter',
    name: 'o1',
  },
  'gpt-4': {
    lastUpdated: '2025-07-19T12:00:35.578Z',
    canonicalSlug: 'openai/gpt-4',
    costPer1kTokens: 0.03,
    source: 'openrouter',
    contextWindow: 8191,
    name: 'gpt-4',
  },
} as const
